---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-values
data:
  global.imageRegistry: "quay.io"
---
apiVersion: bundle.kubegems.io/v1beta1
kind: Bundle
metadata:
  name: nginx
spec:
  kind: helm
  url: https://charts.bitnami.com/bitnami
  version: 10.2.1
  valuesRef:
    - kind: ConfigMap
      name: global-values
  values:
    ingress:
      enabled: true
